export const testData: Array<{ name: string; rate: number; valves: Array<string> }> = [
  { name: 'AA', rate: 0, valves: ['DD', 'II', 'BB'] },
  { name: 'BB', rate: 13, valves: ['CC', 'AA'] },
  { name: 'CC', rate: 2, valves: ['DD', 'BB'] },
  { name: 'DD', rate: 20, valves: ['CC', 'AA', 'EE'] },
  { name: 'EE', rate: 3, valves: ['FF', 'DD'] },
  { name: 'FF', rate: 0, valves: ['EE', 'GG'] },
  { name: 'GG', rate: 0, valves: ['FF', 'HH'] },
  { name: 'HH', rate: 22, valves: ['GG'] },
  { name: 'II', rate: 0, valves: ['AA', 'JJ'] },
  { name: 'JJ', rate: 21, valves: ['II'] },
];

export const data: Array<{ name: string; rate: number; valves: Array<string> }> = [
  { name: 'UU', rate: 24, valves: ['MO', 'FW', 'LQ'] },
  { name: 'EW', rate: 16, valves: ['YZ', 'JK', 'SG'] },
  { name: 'RQ', rate: 0, valves: ['ER', 'ZI'] },
  { name: 'WJ', rate: 25, valves: ['XP'] },
  { name: 'OZ', rate: 17, valves: ['UB', 'HK', 'JM', 'ZK', 'ER'] },
  { name: 'ZM', rate: 23, valves: ['GB'] },
  { name: 'BE', rate: 0, valves: ['AA', 'MJ'] },
  { name: 'YZ', rate: 0, valves: ['KC', 'EW'] },
  { name: 'JX', rate: 0, valves: ['WH', 'KI'] },
  { name: 'QC', rate: 0, valves: ['MJ', 'DW'] },
  { name: 'RU', rate: 14, valves: ['SU'] },
  { name: 'NI', rate: 0, valves: ['AA', 'WH'] },
  { name: 'XP', rate: 0, valves: ['WJ', 'TM'] },
  { name: 'FW', rate: 0, valves: ['UU', 'VO'] },
  { name: 'TM', rate: 0, valves: ['PL', 'XP'] },
  { name: 'KJ', rate: 0, valves: ['MJ', 'CO'] },
  { name: 'LQ', rate: 0, valves: ['UU', 'PE'] },
  { name: 'PE', rate: 0, valves: ['YJ', 'LQ'] },
  { name: 'WH', rate: 11, valves: ['HK', 'JX', 'EZ', 'ZU', 'NI'] },
  { name: 'ZB', rate: 0, valves: ['AA', 'AC'] },
  { name: 'GA', rate: 0, valves: ['AA', 'CO'] },
  { name: 'NH', rate: 0, valves: ['ZU', 'MJ'] },
  { name: 'SG', rate: 0, valves: ['PY', 'EW'] },
  { name: 'MJ', rate: 6, valves: ['KJ', 'BE', 'QC', 'NH', 'EE'] },
  { name: 'QX', rate: 0, valves: ['UD', 'PL'] },
  { name: 'ZK', rate: 0, valves: ['FD', 'OZ'] },
  { name: 'GB', rate: 0, valves: ['ZM', 'FD'] },
  { name: 'ZU', rate: 0, valves: ['NH', 'WH'] },
  { name: 'MO', rate: 0, valves: ['ZI', 'UU'] },
  { name: 'KI', rate: 0, valves: ['DW', 'JX'] },
  { name: 'UD', rate: 19, valves: ['VO', 'PY', 'QX'] },
  { name: 'VO', rate: 0, valves: ['UD', 'FW'] },
  { name: 'PM', rate: 0, valves: ['YF', 'FD'] },
  { name: 'FD', rate: 21, valves: ['ZK', 'PM', 'GB'] },
  { name: 'NQ', rate: 0, valves: ['SU', 'DW'] },
  { name: 'YF', rate: 0, valves: ['ZI', 'PM'] },
  { name: 'CO', rate: 18, valves: ['GA', 'KJ', 'EZ'] },
  { name: 'DW', rate: 10, valves: ['NQ', 'QC', 'KI', 'JK', 'HX'] },
  { name: 'PL', rate: 22, valves: ['KC', 'TM', 'QX'] },
  { name: 'AC', rate: 0, valves: ['ZB', 'YJ'] },
  { name: 'YJ', rate: 15, valves: ['OC', 'PE', 'AC'] },
  { name: 'SU', rate: 0, valves: ['NQ', 'RU'] },
  { name: 'ZI', rate: 20, valves: ['YF', 'RQ', 'MO'] },
  { name: 'EZ', rate: 0, valves: ['WH', 'CO'] },
  { name: 'HX', rate: 0, valves: ['AA', 'DW'] },
  { name: 'EE', rate: 0, valves: ['JM', 'MJ'] },
  { name: 'KC', rate: 0, valves: ['YZ', 'PL'] },
  { name: 'AA', rate: 0, valves: ['ZB', 'BE', 'NI', 'HX', 'GA'] },
  { name: 'UB', rate: 0, valves: ['OC', 'OZ'] },
  { name: 'HK', rate: 0, valves: ['OZ', 'WH'] },
  { name: 'PY', rate: 0, valves: ['UD', 'SG'] },
  { name: 'JK', rate: 0, valves: ['EW', 'DW'] },
  { name: 'OC', rate: 0, valves: ['YJ', 'UB'] },
  { name: 'ER', rate: 0, valves: ['RQ', 'OZ'] },
  { name: 'JM', rate: 0, valves: ['OZ', 'EE'] },
];
